### ISSUE TITLE
href definiti male, nella pagina "Allegato B"

### ISSUE THREAD

**Issue by aborruso** [AgID/lg-opendata-docs#3]
Gli URL non hanno associato correttamente l'href corrispondente

![image](https://github.com/AgID/lg-opendata-docs/assets/30607/105bfd00-0412-4e22-954a-e6f462afbefb)

**Comment by AntoRot** [comment]
Grazie per la segnalazione!
Corretti!

**Comment by aborruso** [comment]
> Grazie per la segnalazione!

Grazie a te
